import Head from 'next/head'
import { Fragment, useRef, useState, useEffect } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const videoRef = useRef(null);
  let snapShotCanvas;

  useEffect(() => {
    async function setup(){
      try {
        snapShotCanvas = document.createElement('canvas');
  
        if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
          const stream = await navigator.mediaDevices.getUserMedia({
            'audio': false,
            'video': {facingMode: 'environment'}
          });
          videoRef.current.srcObject = stream
          videoRef.current.onloadedmetadata = function(e) {
            videoRef.current.play();
          };
        }
    
      } catch(err) {
        console.log(err.name + ": " + err.message);
      }
    }

    setup();

  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <video 
        className="camera__element camera__element--js" 
        autoPlay 
        playsInline
        ref={videoRef}
        >
        </video>
      </main>

      <footer className={styles.footer}>
          Powered by Mariano.
      </footer>
    </div>
  )
}
